### PR TITLE
Filter models on gordo project revision

### LINKED ISSUE #75: Filter models-built on project revision
Now the gordo contains the project version, so we can also filter the `n_models_built` on the version.

### PR DESCRIPTION
**Pull request by milesgranger**
Will close #75 

Regarding route:`/models/<project-name>`

In addition to existing filtering of models matching the project-name/gordo name, return models which match that `Gordo`'s `project-revision` number as well.

### CODE REVIEW

**Comment by epa095** [comment]
Does this affect the nr of built models written back into the gordo?

**Comment by milesgranger** [comment]
Ah, no, I completely disregarded that. :man_facepalming:

**Review by epa095 — APPROVED** [review]
LGTM. Maybe you have even tested it?

**Comment by milesgranger** [comment]
All tested on a real-live cluster. :+1:

**Pull request merged**
